---

- name: Check the Windows registry for the installation path of the VMware Tools.
  ansible.windows.win_reg_stat:
    path: 'HKLM:\SOFTWARE\VMware, Inc.\VMware Tools'
    name: InstallPath
  register: vmware_tools_install_folder

- name: Check version of VMware Tools.
  ansible.windows.win_command: .\VMwareToolboxCmd.exe -v
  args:
    chdir: '{{ vmware_tools_install_folder.value }}'
  register: vmware_toolbox_versionstring
  changed_when: false
  when: vmware_tools_install_folder.exists

- name: Set fact for installed VMware Tools version and build.
  ansible.builtin.set_fact:
    installed_vmware_tools_version:
      - "{{ vmware_toolbox_versionstring.stdout_lines[0] | split(' ') | first | reverse | regex_search('\\d+\\.([\\d+.]+)', '\\1') | first | reverse }}"
      - "{{ vmware_toolbox_versionstring.stdout_lines[0] | split(' ') | last | regex_search('\\(build-(\\d+)\\)', '\\1') | first }}"
  when:
    - vmware_tools_install_folder.exists
    - vmware_toolbox_versionstring.stdout is defined
    - vmware_toolbox_versionstring.stdout | length > 1

- name: Block for getting content from VMware Tools URL
  when: >
    installed_vmware_tools_version is not defined or
    (installed_vmware_tools_version is defined and installed_vmware_tools_version[0] is version(vmware_tools_version, '<'))
  block:
    - name: Get content from {{ vmware_tools_url }}.
      ansible.windows.win_uri:
        url: '{{ vmware_tools_url }}'
        return_content: true
      register: vmware_site_http_output

    - name: Set fact for filename for VMware Tools iso.
      ansible.builtin.set_fact:
        vmware_tools_iso_filename: "{{ vmware_site_http_output.content | regex_search('.*(VMware-tools-windows-[\\d.-]+\\.iso).*', '\\1') }}"
      when: vmware_site_http_output.status_code | int  == 200

    - name: Set fact for available VMware Tools version and build.
      ansible.builtin.set_fact:
        available_vmware_tools_version:
          - "{{ vmware_tools_iso_filename | regex_search('VMware-tools-windows-([\\d.]+)-(\\d+).iso', '\\1') | first }}"
          - "{{ vmware_tools_iso_filename | regex_search('VMware-tools-windows-([\\d.]+)-(\\d+).iso', '\\2') | first }}"
