---

- name: Configure VMware Tools timesync.
  when: installed_vmware_tools_version is defined
  block:

    - name: Read current VMware Tools timesync setting.
      become: true
      ansible.windows.win_command: .\VMwareToolboxCmd.exe timesync status
      args:
        chdir: '%ProgramFiles%\\VMware\VMware Tools'
      register: vmwaretoolboxcmd
      changed_when: false
      failed_when: ("Enabled" not in vmwaretoolboxcmd.stdout_lines) and
                    ("Disabled" not in vmwaretoolboxcmd.stdout_lines)

    - name: Enable VMware Tools timesync.
      become: true
      ansible.windows.win_command: .\VMwareToolboxCmd.exe timesync enable
      args:
        chdir: '%ProgramFiles%\VMware\VMware Tools'
      when: '"Enabled" not in vmwaretoolboxcmd.stdout_lines and ansible_role_vmware_tools_time_sync'

    - name: Disable VMware Tools timesync.
      become: true
      ansible.windows.win_command: .\VMwareToolboxCmd.exe timesync disable
      args:
        chdir: '%ProgramFiles%\VMware\VMware Tools'
      when: '"Disabled" not in vmwaretoolboxcmd.stdout_lines and not ansible_role_vmware_tools_time_sync'
