---

- name: Create a temporary directory for download.
  ansible.windows.win_tempfile:
    state: directory
  register: vmware_tools_dl_temp

- name: Download ISO from VMware Tools site.
  ansible.windows.win_get_url:
    checksum_algorithm: sha256
    checksum: "{{ vmware_tools_sha256sums[available_vmware_tools_version | join('-')] }}"
    url: '{{ vmware_tools_url }}/{{ vmware_tools_iso_filename | first }}'
    validate_certs: true
    dest: '{{ vmware_tools_dl_temp.path }}'
  retries: 10
  delay: 10

- name: Mount VMware Tools ISO file.
  community.windows.win_disk_image:
    image_path: '{{ vmware_tools_dl_temp.path }}\{{ vmware_tools_iso_filename | first }}'
    state: present
  register: vmware_tools_iso_mount

- name: Extract installer files to tempdir.
  ansible.windows.win_command: "{{ vmware_tools_installer_bin_name }} /A {{ vmware_tools_dl_temp.path }}"
  args:
    chdir: '{{ vmware_tools_iso_mount.mount_paths[0] }}'

- name: Find MSI file in tempdir.
  ansible.windows.win_find:
    paths: '{{ vmware_tools_dl_temp.path }}'
    patterns: '*.msi'
  register: vm_tools_msi_installer_search

- name: Set fact for productid.
  ansible.builtin.set_fact:
    vmware_tools_productid: "{{ vm_tools_msi_installer_search.files[0].filename | regex_search('{([A-Z0-9-]+)}.msi', '\\1') | first }}"

- name: Install VMware Tools (version {{ vmware_tools_version }}) using {{ vmware_tools_installer_bin_name }}.
  become: true
  ansible.windows.win_package:
    path: "{{ vmware_tools_iso_mount.mount_paths[0] }}\\{{ vmware_tools_installer_bin_name }}"
    product_id: '{{ vmware_tools_productid }}'
    arguments: ' /S /v "/qn REBOOT=R ADDLOCAL=ALL {% if vmware_tools_remove_features|length > 0 %}REMOVE={{ vmware_tools_remove_features | join(", ") }}{% endif %}"'
    state: present
    expected_return_code: [0, 1641, 3010]
  async: 300
  poll: 5
  register: vmware_tools_install

- name: Reboot after VMware Tools install if needed.
  become: true
  ansible.windows.win_reboot:
    reboot_timeout: 600
  no_log: false
  when: vmware_tools_install.reboot_required | bool

- name: Wait for vmtoolsd processes.
  community.windows.win_wait_for_process:
    process_name_exact: vmtoolsd
    process_min_count: 1
    state: present
    sleep: 10
    timeout: 300
  no_log: true

- name: Unmount VMware Tools ISO file.
  community.windows.win_disk_image:
    image_path: '{{ vmware_tools_dl_temp.path }}\{{ vmware_tools_iso_filename | first }}'
    state: absent

- name: Delete VMware Tools installer.
  become: true
  ansible.windows.win_file:
    path: '{{ vmware_tools_dl_temp.path }}'
    state: absent
