---

- name: Assert that role is executed on a supported Operating System
  ansible.builtin.assert:
    that:
      - ansible_distribution is search("Microsoft Windows Server 2016") or
        ansible_distribution is search("Microsoft Windows Server 2019") or
        ansible_distribution is search("Microsoft Windows Server 2022") or
        ansible_distribution is search("Microsoft Windows Server 2025") or
        ansible_distribution is search("Microsoft Windows 10") or
        ansible_distribution is search("Microsoft Windows 11")
      - "'64' in ansible_architecture"
    msg: "{{ ansible_distribution }} {{ ansible_architecture }} is not a supported Operating System for this role."
    quiet: true


- name: Run install and configure on supported Operating systems.
  block:
    - name: Include check tasks.
      ansible.builtin.include_tasks:
        file: check.yml
    - name: Include install tasks.
      ansible.builtin.include_tasks:
        file: install.yml
      when: >
        installed_vmware_tools_version is not defined or
        (installed_vmware_tools_version is defined and installed_vmware_tools_version[0] is version(vmware_tools_version, '<'))
    - name: Include configure tasks.
      ansible.builtin.include_tasks:
        file: configure.yml
