---

- name: Assert that role is executed on a supported Operating System
  ansible.builtin.assert:
    that: >
      ansible_distribution is search("Microsoft Windows Server 2012") or ansible_distribution is search("Microsoft Windows Server 2016")
      or ansible_distribution is search("Microsoft Windows Server 2019") or ansible_distribution is search("Microsoft Windows Server 2022")
    msg: "{{ ansible_distribution }} is not a supported Operating System for this role."

- name: Run install and configure on supported Operating systems.
  block:
    - name: Include check tasks.
      ansible.builtin.import_tasks:
        file: check.yml
    - name: Include install tasks.
      ansible.builtin.import_tasks:
        file: install.yml
    - name: Include configure tasks.
      ansible.builtin.import_tasks:
        file: configure.yml
